print(
    '''
    # WHAT THIS SCRIPT DOES:
    # Creates a table overview of the patient clusters[phenotypes] (excel file)
    # not as detailed as the one generated by analyse_results.py
    # but with most important features for showing in main part of manusript
    # notable important columns (per cluster):
        # chronic conditions used by TARGET-HF
        # n -> count
        # male -> Sex
        # HF -> Heart Failure
        # t_birth -> age
        # t_dur -> follow-up duration
        # t_flwp_start -> follow-up start date
        # follow_up_effective -> Follw-up end date
        # targetHF_score -> TARGET-HF risk score
'''
)

from try_utils import *
from constants import *
from sys import exit

IS_DEBUG = parse_commandline_args(verbose=True)["IS_DEBUG"]
SUBSAMPLE_DATA = parse_commandline_args()["SUBSAMPLE_DATA"]
subsampled_str = "" if not SUBSAMPLE_DATA else "_SUBSAMPLED"

check_if_debugging(IS_DEBUG)

outfile_infix = f"{subsampled_str}"
logfile = f'{os.path.basename(__file__)[:-3]}_{outfile_infix}.log'
logger = get_logger_fn(logfile)
logger(f"Starting ...")

import random
import numpy as np
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

pickle_exists = lambda f: try_pickle_exists(f, subsampled=SUBSAMPLE_DATA)
read_pickle = lambda f: try_read_pickle(f, subsampled=SUBSAMPLE_DATA)
save_pickle = lambda f, o: try_save_pickle(f, o, subsampled=SUBSAMPLE_DATA)
cached_call = lambda fn, override_cache=F, **kwargs : try_cached_call(fn, io_r=read_pickle, io_c=pickle_exists, io_w=save_pickle, override_cache=override_cache, **kwargs)
# Boilerplate end

import analyse_results_util as ar_util

logger('')
tmp = ar_util.load_cohort(override_saved_file=F, with_gmm_dummies=F)
cohort = tmp['cohort']
vars_used = tmp['vars_used']

# pats_dict = read_pickle('pats_dict_merged.pkl')
# pids = vals(cohort.id_str)
# pats_dict = {k:pats_dict[k] for k in pids}

get_first_consult_dt = lambda e: min([j['journal_datetime'] for j in e['JOURNALS']]) if e['JOURNALS'] != [] else 999999999
get_first_date_ep_or_consult = lambda p: min([ min(e['episode_start_date'], get_first_consult_dt(e)) for e in p['Episodes']])

def set_cohort_flwp_start_end(pats_dict, cohort):
    first_dates = [get_first_date_ep_or_consult(p) for p in pats_dict.values()]
    cohort['t_flwp_start'] = first_dates
    # fix var_obs_end for HF+ cases (it was NaN..) VAR_FOLLOW_UP_DATE
    cohort.loc[pd.isnull(cohort[VAR_OBSERVATION_END]), [VAR_OBSERVATION_END]] = cohort[pd.isnull(cohort[VAR_OBSERVATION_END])][VAR_FOLLOW_UP_DATE]
    cohort['t_dur'] = cohort[VAR_OBSERVATION_END] - cohort.t_flwp_start
    return cohort
    # try_table(cohort['t_dur'])

# todo: get number of consults
# cohort = cached_call(set_cohort_flwp_start_end, override_cache=F, pats_dict=pats_dict, cohort=cohort)
cohort = cached_call(set_cohort_flwp_start_end, override_cache=F, pats_dict={}, cohort=cohort)

# coi = columns of interest
coi = ['0_24_n_eps_', 'targetHF_score', 'follow_up_effective'] + [x for x in cns(cohort) if x.startswith('t_') and not x.endswith('_x')]
coi = try_sd(coi, ['t_VHD', 't_AF', 't_min'])
#coi = [x[:-3] if x.endswith('_y') else x for x in coi]
non_bin_coi = sorted(['0_24_n_eps_', 't_birth', 'targetHF_score', 'follow_up_effective', 't_dur', 't_flwp_start'])
bin_coi = try_sd(coi, non_bin_coi)
cols = coi + ['gmm_cls'] 

def gen_groups(df, col='gmm_cls'):
    for col_v, ss_df in df.groupby([col]):
        yield col_v, ss_df
    yield "ALL", df


bin_coi_vcs = {k:nuniq(cohort[k]) for k in bin_coi}
needs_binerise = [k for k,v in bin_coi_vcs.items() if v > 2]
sex_map = { 'V' : 0, 'M' : 1, 'N': None, 'O': None}
cohort['is_male'] = [sex_map[v] for v in cohort['sex']]
bin_coi += ['is_male']
cols += ['is_male']
try_table(cohort['is_male'])
for c in needs_binerise:
    cohort[c] = ~pd.isnull(cohort[c])

res = []
bin_coi = sorted(bin_coi)
bin_coi_fancy = [x[2:-2] if x.endswith('_y') else x[2:] for x in bin_coi]
bin_coi_fancy = [x.replace('_', ' ').strip() for x in bin_coi_fancy]
# bin_coi_fancy = sorted(bin_coi_fancy)
res_colnames = ['Cluster ID', 'n'] 
for bc in bin_coi_fancy:
    res_colnames = res_colnames + [bc, f"{bc}%", f"{bc}(%)"]
for nbc in non_bin_coi:
    res_colnames = res_colnames + [nbc, f"{nbc}_IQR", f"{nbc}(IQR)" ]

res_colnames += ['CR per 1000 person-years']
precisions_non_bin_coi = { c:0 for c in non_bin_coi}
precisions_non_bin_coi['targetHF_score'] = 1
precisions_non_bin_coi['0_24_n_eps_'] = 1


cohort.t_birth = round((cohort['follow_up_LAST'] +  cohort['age_days'] ) / 365)  # convert to age years, todo: rename t_birth to age_days

for gmm_id, gmm_df in gen_groups(cohort[cols], 'gmm_cls'):
    c_res = [gmm_id, nrow(gmm_df)]
    # % stuff
    for bc, bcf in zip(bin_coi, bin_coi_fancy): # try_print_list([ f"bc={a} \#->{b}" for a,b in zip(bin_coi, bin_coi_fancy)], logger)
        c_df = gmm_df[~pd.isnull(gmm_df[bc])]
        n1s = try_table(c_df[bc]).to_dict()[1]
        c_res+=[n1s]
        percent_1s = 100*n1s / nrow(c_df)
        c_res+=[percent_1s]
        c_res+=[f"{n1s} ({percent_1s:.1f})" ]

    # IQR stuff
    for nbc in non_bin_coi:
        c_df = gmm_df[~pd.isnull(gmm_df[nbc])] # todo: missing count
        decimals = precisions_non_bin_coi[nbc]
        c_iqr = np.quantile(c_df[nbc], [0.25, 0.75])
        c_iqr = f"{c_iqr[0]:.{decimals}f}; {c_iqr[1]:.{decimals}f}"
        c_median = np.median(c_df[nbc])
        if nbc not in ['targetHF_score', 't_dur', 't_birth', '0_24_n_eps_']:
            c_median = f"'{conv_date_days_to_str(c_median)}'"
            c_iqr = [conv_date_days_to_str(v) for v in np.quantile(c_df[nbc], [0.25, 0.75])]
            c_iqr = f"{c_iqr[0]}; {c_iqr[1]}"
        c_res+=[c_median]
        c_res+=[c_iqr]
        if nbc in ['targetHF_score', 't_dur', 't_birth', '0_24_n_eps_']:
            c_res+=[f"{c_median:.{decimals}f} ({c_iqr})" ]
        else:
            c_res+=[f"{c_median} ({c_iqr})" ]
    
    c_flwp_dur = gmm_df.t_dur.sum()
    c_n_cases = gmm_df.t_HF.sum()
    c_IR = (1000*c_n_cases) / (c_flwp_dur/DAYS_IN_YEAR) # i.e., *X* number of HF cases per 1000 person-years
    c_res+= [c_IR]

        
    res  = res + [c_res]
    # break


out_df = pd.DataFrame.from_records(res)
out_df.columns = res_colnames
out_df = out_df.sort_values(by=['HF%'], ascending=F)

if "make columns nice" != "columns nice make":
    cols_ordered = [
            'Cluster ID',
            'n',
            't_birth',
            't_birth_IQR',
            't_birth(IQR)',
            'male',
            'male%',
            'male(%)',
            'HF',
            'HF%',
            'HF(%)',
            'CR per 1000 person-years',
            '0_24_n_eps_',
            '0_24_n_eps__IQR',
            '0_24_n_eps_(IQR)',
            'tobacco use',
            'tobacco use%',
            'tobacco use(%)',         
            'alcohol abuse',
            'alcohol abuse%',
            'alcohol abuse(%)',
            'obesity',
            'obesity%',
            'obesity(%)',
            'material deprivation',
            'material deprivation%',
            'material deprivation(%)',
            'cvd in family',
            'cvd in family%',
            'cvd in family(%)',
            'hypertension',
            'hypertension%',
            'hypertension(%)',
            'diabetes mellitus',
            'diabetes mellitus%',
            'diabetes mellitus(%)',
            'coronary artery disease',
            'coronary artery disease%',
            'coronary artery disease(%)',
            'atrial fibrillation',
            'atrial fibrillation%',
            'atrial fibrillation(%)',
            'heart murmur',
            'heart murmur%',
            'heart murmur(%)',
            'valvular heart disease',
            'valvular heart disease%',
            'valvular heart disease(%)',
            'stroke',
            'stroke%',
            'stroke(%)',
            'copd',
            'copd%',
            'copd(%)',
            'chronic kidney disease',
            'chronic kidney disease%',
            'chronic kidney disease(%)',

            'targetHF_score',
            'targetHF_score_IQR',
            'targetHF_score(IQR)',
            't_dur',
            't_dur_IQR',
            't_dur(IQR)',
            't_flwp_start',
            't_flwp_start_IQR',
            't_flwp_start(IQR)',
            'follow_up_effective',
            'follow_up_effective_IQR',
            'follow_up_effective(IQR)'
    ]

    out_df = out_df[cols_ordered]
    cols_pretty = [
            'Cluster ID',
            'N',
            'Age ',
            'Age  (IQR only)',
            'Age (IQR)',
            'Male',
            'Male%',
            'Male(%)',
            'HF',
            'HF%',
            'HF(%)',
            'CR per 1000 person-years',
            '#Episodes',
            '#Episodes (IQR only)',
            '#Episodes (IQR)',
            'Tobacco use',
            'Tobacco use%',
            'Tobacco use(%)',         
            'Alcohol abuse',
            'Alcohol abuse%',
            'Alcohol abuse(%)',
            'Obesity',
            'Obesity%',
            'Obesity(%)',
            'Material deprivation',
            'Material deprivation%',
            'Material deprivation(%)',
            'Family history of CVD',
            'Family history of CVD%',
            'Family history of CVD(%)',
            'Hypertension',
            'Hypertension%',
            'Hypertension(%)',
            'Diabetes mellitus',
            'Diabetes mellitus%',
            'Diabetes mellitus(%)',
            'Coronary artery disease',
            'Coronary artery disease%',
            'Coronary artery disease(%)',
            'Atrial fibrillation',
            'Atrial fibrillation%',
            'Atrial fibrillation(%)',
            'Heart murmur',
            'Heart murmur%',
            'Heart murmur(%)',
            'Valvular heart disease',
            'Valvular heart disease%',
            'Valvular heart disease(%)',
            'Stroke',
            'Stroke%',
            'Stroke(%)',
            'COPD',
            'COPD%',
            'COPD(%)',
            'CKD',
            'CKD%',
            'CKD(%)',
            'TARGET-HF score',
            'TARGET-HF score (IQR only)',
            'TARGET-HF score(IQR)',
            'Follow-up duration days',
            'Follow-up duration days (IQR only)',
            'Follow-up duration days(IQR)',
            'Follow-up start',
            'Follow-up start (IQR only)',
            'Follow-up start(IQR)',
            'Follow-up end',
            'Follow-up end (IQR only)',
            'Follow-up end(IQR)'
    ]
    out_df.columns = cols_pretty


out_df = out_df.T


out_df.to_excel('excel/summary_clusters.xlsx')
    
